title: The 6th IEEE Cyber Science and Technology Congress (CyberSciTech 2021) 
description: CyberSciTech 2021



baseurl: /2021
color-scheme: "#1B365D" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
